-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-01 15:13:51 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--   Group: G288
--   Member names: Enkhjin Erdenebulgan, Rizky Sanditya Arief, Yuebo Feng

set echo on
SPOOL pat_schema_output.txt

DROP TABLE driver CASCADE CONSTRAINTS;

DROP TABLE driver_language CASCADE CONSTRAINTS;

DROP TABLE driver_training CASCADE CONSTRAINTS;

DROP TABLE feature CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE location CASCADE CONSTRAINTS;

DROP TABLE noc CASCADE CONSTRAINTS;

DROP TABLE official CASCADE CONSTRAINTS;

DROP TABLE training CASCADE CONSTRAINTS;

DROP TABLE trip CASCADE CONSTRAINTS;

DROP TABLE vehicle CASCADE CONSTRAINTS;

DROP TABLE vehicle_feature CASCADE CONSTRAINTS;

DROP TABLE vehicle_manufacturer CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE driver (
    driver_id                 CHAR(4) NOT NULL,
    driver_license_no         CHAR(18) NOT NULL,
    driver_given_name         VARCHAR2(20),
    driver_family_name        VARCHAR2(20),
    driver_dob                DATE NOT NULL,
    driver_total_training     NUMBER(3) NOT NULL,
    driver_security_clearance CHAR(1) DEFAULT 'R' NOT NULL,
    driver_suspended_flag     CHAR(1) DEFAULT 'F' NOT NULL
);

ALTER TABLE driver
    ADD CONSTRAINT chk_driver_security_clearance CHECK ( driver_security_clearance IN ( 'F', 'R' ) );

ALTER TABLE driver
    ADD CONSTRAINT chk_driver_suspended CHECK ( driver_suspended_flag IN ( 'F', 'T' ) );

COMMENT ON COLUMN driver.driver_id IS
    'ID of driver';

COMMENT ON COLUMN driver.driver_license_no IS
    'Driver''s license number of driver';

COMMENT ON COLUMN driver.driver_given_name IS
    'Given name of driver';

COMMENT ON COLUMN driver.driver_family_name IS
    'Family name of driver';

COMMENT ON COLUMN driver.driver_dob IS
    'Date of birth of driver';

COMMENT ON COLUMN driver.driver_total_training IS
    'Number of total trainings of driver';

COMMENT ON COLUMN driver.driver_security_clearance IS
    'Security clearance level of driver, F=Full, R=Restricted';

COMMENT ON COLUMN driver.driver_suspended_flag IS
    'Flag of driver suspended status, T=True/suspended, F=False/not suspended';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driver_id );

CREATE TABLE driver_language (
    language_code CHAR(2) NOT NULL,
    driver_id     CHAR(4) NOT NULL
);

COMMENT ON COLUMN driver_language.language_code IS
    'Code of language';

COMMENT ON COLUMN driver_language.driver_id IS
    'ID of driver';

ALTER TABLE driver_language ADD CONSTRAINT driver_language_pk PRIMARY KEY ( language_code,
                                                                            driver_id );

CREATE TABLE driver_training (
    driver_id         CHAR(4) NOT NULL,
    dt_completed_date DATE NOT NULL,
    training_code     CHAR(10) NOT NULL
);

COMMENT ON COLUMN driver_training.driver_id IS
    'ID of driver';

COMMENT ON COLUMN driver_training.dt_completed_date IS
    'Completed date of training';

COMMENT ON COLUMN driver_training.training_code IS
    'Code of training';

ALTER TABLE driver_training
    ADD CONSTRAINT driver_training_pk PRIMARY KEY ( driver_id,
                                                    training_code,
                                                    dt_completed_date );

CREATE TABLE feature (
    feature_code CHAR(3) NOT NULL,
    feature_name VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN feature.feature_code IS
    'Feature code';

COMMENT ON COLUMN feature.feature_name IS
    'Feature name';

ALTER TABLE feature ADD CONSTRAINT vehicle_feature_pk PRIMARY KEY ( feature_code );

CREATE TABLE language (
    language_code CHAR(2) NOT NULL,
    language_name VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN language.language_code IS
    'Code of language';

COMMENT ON COLUMN language.language_name IS
    'Name of language';

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( language_code );

CREATE TABLE location (
    location_id      CHAR(2) NOT NULL,
    location_name    VARCHAR2(50) NOT NULL,
    location_type    VARCHAR2(20) NOT NULL,
    location_address VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN location.location_id IS
    'ID of location';

COMMENT ON COLUMN location.location_name IS
    'Name of location';

COMMENT ON COLUMN location.location_type IS
    'Type of location';

COMMENT ON COLUMN location.location_address IS
    'Address of location';

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( location_id );

CREATE TABLE noc (
    noc_ioc_code     CHAR(3) NOT NULL,
    noc_country_name VARCHAR2(20) NOT NULL,
    noc_population   NUMBER(10) NOT NULL
);

COMMENT ON COLUMN noc.noc_ioc_code IS
    'NOC code';

COMMENT ON COLUMN noc.noc_country_name IS
    'Name of NOC';

COMMENT ON COLUMN noc.noc_population IS
    'Population of NOC';

ALTER TABLE noc ADD CONSTRAINT noc_pk PRIMARY KEY ( noc_ioc_code );

CREATE TABLE official (
    official_id          CHAR(7) NOT NULL,
    official_given_name  VARCHAR2(20),
    official_family_name VARCHAR2(20),
    official_role        VARCHAR2(30) NOT NULL,
    noc_ioc_code         CHAR(3) NOT NULL,
    chef_de_mission_id   CHAR(7)
);

COMMENT ON COLUMN official.official_id IS
    'ID number of official';

COMMENT ON COLUMN official.official_given_name IS
    'Given name of official';

COMMENT ON COLUMN official.official_family_name IS
    'Family name of official';

COMMENT ON COLUMN official.official_role IS
    'Role of official';

COMMENT ON COLUMN official.noc_ioc_code IS
    'NOC code';

COMMENT ON COLUMN official.chef_de_mission_id IS
    'ID number of official';

ALTER TABLE official ADD CONSTRAINT official_pk PRIMARY KEY ( official_id );

CREATE TABLE training (
    training_code          CHAR(10) NOT NULL,
    training_length        NUMBER(2) NOT NULL,
    training_name          VARCHAR2(30) NOT NULL,
    training_desc          VARCHAR2(50) NOT NULL,
    training_expiry_period NUMBER(2) NOT NULL
);

COMMENT ON COLUMN training.training_code IS
    'Code of training';

COMMENT ON COLUMN training.training_length IS
    'Length of training (day)';

COMMENT ON COLUMN training.training_name IS
    'Name of training';

COMMENT ON COLUMN training.training_desc IS
    'Description of training';

COMMENT ON COLUMN training.training_expiry_period IS
    'Expiry period of training module (in months)';

ALTER TABLE training ADD CONSTRAINT training_pk PRIMARY KEY ( training_code );

CREATE TABLE trip (
    trip_id                        CHAR(4) NOT NULL,
    trip_passnum                   NUMBER(2) NOT NULL,
    trip_intended_pickup_datetime  DATE NOT NULL,
    trip_actual_pickup_datetime    DATE,
    trip_intended_dropoff_datetime DATE NOT NULL,
    trip_actual_dropoff_datetime   DATE,
    official_id                    CHAR(7) NOT NULL,
    driver_id                      CHAR(4) NOT NULL,
    vehicle_id                     CHAR(17) NOT NULL,
    pickup_location_id             CHAR(2) NOT NULL,
    dropoff_location_id            CHAR(2) NOT NULL,
    language_code                  CHAR(2) NOT NULL
);

COMMENT ON COLUMN trip.trip_id IS
    'ID of trip';

COMMENT ON COLUMN trip.trip_passnum IS
    'Number of passengers of trip';

COMMENT ON COLUMN trip.trip_intended_pickup_datetime IS
    'Intended pickup date & time ';

COMMENT ON COLUMN trip.trip_actual_pickup_datetime IS
    'Actual pickup date & time ';

COMMENT ON COLUMN trip.trip_intended_dropoff_datetime IS
    'Intended dropoff date & time ';

COMMENT ON COLUMN trip.trip_actual_dropoff_datetime IS
    'Actual dropoff date & time ';

COMMENT ON COLUMN trip.official_id IS
    'ID number of official';

COMMENT ON COLUMN trip.driver_id IS
    'ID of driver';

COMMENT ON COLUMN trip.vehicle_id IS
    'ID of vehicle';

COMMENT ON COLUMN trip.pickup_location_id IS
    'ID of location';

COMMENT ON COLUMN trip.dropoff_location_id IS
    'ID of location';

COMMENT ON COLUMN trip.language_code IS
    'Code of language';

ALTER TABLE trip ADD CONSTRAINT trip_pk PRIMARY KEY ( trip_id );

CREATE TABLE vehicle (
    vehicle_id       CHAR(17) NOT NULL,
    vehicle_reg_num  CHAR(7) NOT NULL,
    vehicle_model    VARCHAR2(30) NOT NULL,
    vehicle_year     DATE NOT NULL,
    vehicle_odometer NUMBER(6) NOT NULL,
    vehicle_seatnum  NUMBER(2) NOT NULL
);

COMMENT ON COLUMN vehicle.vehicle_id IS
    'ID of vehicle';

COMMENT ON COLUMN vehicle.vehicle_reg_num IS
    'Registration number of vehicle';

COMMENT ON COLUMN vehicle.vehicle_model IS
    'Model of vehicle';

COMMENT ON COLUMN vehicle.vehicle_year IS
    'Year of vehicle';

COMMENT ON COLUMN vehicle.vehicle_odometer IS
    'Current odometer of vehicle';

COMMENT ON COLUMN vehicle.vehicle_seatnum IS
    'Seats number of vehicle';

ALTER TABLE vehicle ADD CONSTRAINT vehicle_pk PRIMARY KEY ( vehicle_id );

CREATE TABLE vehicle_feature (
    vehicle_id   CHAR(17) NOT NULL,
    feature_code CHAR(3) NOT NULL
);

COMMENT ON COLUMN vehicle_feature.vehicle_id IS
    'ID of vehicle';

COMMENT ON COLUMN vehicle_feature.feature_code IS
    'Feature code';

ALTER TABLE vehicle_feature ADD CONSTRAINT vehicle_feature_pkv1 PRIMARY KEY ( vehicle_id,
                                                                              feature_code );

CREATE TABLE vehicle_manufacturer (
    vehicle_model VARCHAR2(30) NOT NULL,
    vehicle_make  VARCHAR2(30) NOT NULL,
    vehicle_id    CHAR(17) NOT NULL
);

COMMENT ON COLUMN vehicle_manufacturer.vehicle_model IS
    'Model of vehicle';

COMMENT ON COLUMN vehicle_manufacturer.vehicle_make IS
    'Make of vehicle';

COMMENT ON COLUMN vehicle_manufacturer.vehicle_id IS
    'ID of vehicle';

ALTER TABLE vehicle_manufacturer ADD CONSTRAINT vehicle_manufacture_pk PRIMARY KEY ( vehicle_model );

ALTER TABLE driver_language
    ADD CONSTRAINT driver_driver_language FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE driver_training
    ADD CONSTRAINT driver_driver_training FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE trip
    ADD CONSTRAINT driver_trip FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE vehicle_feature
    ADD CONSTRAINT feature_vehicle_feature FOREIGN KEY ( feature_code )
        REFERENCES feature ( feature_code );

ALTER TABLE driver_language
    ADD CONSTRAINT language_driver_language FOREIGN KEY ( language_code )
        REFERENCES language ( language_code );

ALTER TABLE trip
    ADD CONSTRAINT language_trip FOREIGN KEY ( language_code )
        REFERENCES language ( language_code );

ALTER TABLE trip
    ADD CONSTRAINT location_trip FOREIGN KEY ( pickup_location_id )
        REFERENCES location ( location_id );

ALTER TABLE trip
    ADD CONSTRAINT location_tripv1 FOREIGN KEY ( dropoff_location_id )
        REFERENCES location ( location_id );

ALTER TABLE official
    ADD CONSTRAINT noc_official FOREIGN KEY ( noc_ioc_code )
        REFERENCES noc ( noc_ioc_code );

ALTER TABLE official
    ADD CONSTRAINT official_official FOREIGN KEY ( chef_de_mission_id )
        REFERENCES official ( official_id );

ALTER TABLE trip
    ADD CONSTRAINT official_trip FOREIGN KEY ( official_id )
        REFERENCES official ( official_id );

ALTER TABLE driver_training
    ADD CONSTRAINT training_driver_training FOREIGN KEY ( training_code )
        REFERENCES training ( training_code );

ALTER TABLE vehicle_manufacturer
    ADD CONSTRAINT vechile_manufacture FOREIGN KEY ( vehicle_id )
        REFERENCES vehicle ( vehicle_id );

ALTER TABLE vehicle_feature
    ADD CONSTRAINT vehicle_feature FOREIGN KEY ( vehicle_id )
        REFERENCES vehicle ( vehicle_id );

ALTER TABLE trip
    ADD CONSTRAINT vehicle_trip FOREIGN KEY ( vehicle_id )
        REFERENCES vehicle ( vehicle_id );

SPOOL off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
